gradsflow/gradsflow

.github/labeler.yml, .github/workflows/main.yml, .gitignore, .pre-commit-config.yaml, Makefile, README.md, docs/CNAME, docs/index.md, examples/autoclassifier.py, gradsflow/__init__.py, gradsflow/autoclassifier/__init__.py, gradsflow/autoclassifier/image.py, gradsflow/automodel/__init__.py, gradsflow/automodel/automodel.py, gradsflow/logging.py, gradsflow/utility/common.py, pyproject.toml, sonar-project.properties, tests/__init__.py, tests/autoclassifier/test_image.py, tests/automodel/test_automodel.py, tests/utility/test_common.py, tests/utility/test_utility.py
=> Add AutoImageClassifier

.deepsource.toml, .github/workflows/main.yml, Makefile, docs/gradsflow/autoclassifier.md, docs/gradsflow/automodel.md, docs/requirements.txt, gradsflow/autoclassifier/base.py, gradsflow/automodel/automodel.py, mkdocs.yml, pyproject.toml, tests/__init__.py, tests/__main__.py, tests/autoclassifier/test_image.py, tests/autoclassifier/test_text.py
Create docs from the docstring and fix failing test
=> auto docstring

README.md, docs/index.md, docs/requirements.txt, gradsflow/__init__.py, gradsflow/automodel/automodel.py, mkdocs.yml, tests/automodel/test_automodel.py
=> fix docs ci

.github/workflows/latest-changes.yml, .github/workflows/release-notes.jinja2, CONTRIBUTING.md, README.md, docs/CHANGELOG.md, docs/gradsflow/utility.md, docs/index.md, mkdocs.yml
=> 📚 update documentation - added citation, acknowledgments, docstrings automation

examples/nbs/03_TextSummarization.ipynb
=> Adding example notebook for AutoSummarization

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/labeler.yml, .github/pull_request_template.md, gradsflow/core/autoclassifier.py, gradsflow/core/automodel.py, pyproject.toml, tests/core/test_automodel.py
`AutoModel` which is core of `gradsflow` has low coverage. This PR adds tests for the same.
=> ✅ test automodel

.github/workflows/publish-to-test-pypi.yml, .readthedocs.yaml, docs/overrides/main.html, pyproject.toml
=> Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

gradsflow/autotasks/autoclassification/image.py, gradsflow/autotasks/autoclassification/text.py, gradsflow/autotasks/autosummarization.py, gradsflow/core/automodel.py, tests/core/test_automodel.py
=> 🚀 feature/fix train arguments docs

gradsflow/__init__.py, pyproject.toml
=> upgrade flash

.pre-commit-config.yaml, docs/gradsflow/data.md, examples/nbs/01-ImageClassification.ipynb, examples/nbs/04-RayDataset.ipynb, gradsflow/__init__.py, gradsflow/core/autodata.py, gradsflow/core/automodel.py, gradsflow/core/autotrainer.py, gradsflow/data/__init__.py, gradsflow/data/image.py, gradsflow/data/ray_dataset.py, mkdocs.yml, pyproject.toml, tests/data/__init__.py, tests/data/test_image.py, tests/data/test_ray_dataset.py
Fixes #60 
Support remote dataset data loading with `ray.data` and torch DataLoader
=> add RayDataset

gradsflow/data/image.py
=> optional ray_data

README.md, docs/index.md, docs/requirements.txt, examples/nbs/01-ImageClassification.ipynb, examples/nbs/05-model_fit.ipynb, gradsflow/__init__.py, gradsflow/core/automodel.py, gradsflow/core/backend.py, gradsflow/core/base.py, gradsflow/core/callbacks.py, gradsflow/core/data.py, gradsflow/model/base.py, gradsflow/model/model.py, gradsflow/model/tracker.py, gradsflow/tasks/autotasks.py, pyproject.toml, setup.cfg, tests/__main__.py, tests/core/test_automodel.py, tests/core/test_autotrainer.py, tests/model/test_model.py, tests/tasks/test_autotasks.py, tests/tasks/test_image.py
=> 🚀 refactor training loop

gradsflow/__init__.py, gradsflow/model/model.py
=> set `model.eval()` in val_epoch

README.md, docs/index.md, examples/nbs/06-AutoModel_fit.ipynb, gradsflow/data/image.py, gradsflow/models/model.py, gradsflow/tuner/automodel.py, mkdocs.yml, tests/data/test_image.py, tests/tuner/test_automodel.py, tests/tuner/test_tuner.py
=> 🧪add tests

.github/workflows/main.yml, docs/requirements.txt, examples/nbs/05-model_fit.ipynb, examples/src/models/hello_world.py, gradsflow/callbacks/__init__.py, gradsflow/callbacks/callbacks.py, gradsflow/callbacks/progress.py, gradsflow/callbacks/raytune.py, gradsflow/callbacks/runner.py, gradsflow/core/backend.py, gradsflow/core/data.py, gradsflow/data/image.py, gradsflow/models/base.py, gradsflow/models/model.py, gradsflow/models/tracker.py, gradsflow/tuner/automodel.py, pyproject.toml, tests/models/test_model.py, tests/tuner/test_automodel.py
Enhance Callback implementation and convert `rich.progress` to Callback
=> feature/improve callbacks & 🤑 ProgressCallback

gradsflow/models/base.py, gradsflow/models/model.py
=> fix step update

gradsflow/models/base.py, gradsflow/models/model.py, tests/models/test_model.py
=> 🤗 make HF accelerator optional

docs/CHANGELOG.md, docs/gradsflow/models.md, docs/gradsflow/models/base.md, docs/gradsflow/models/model.md, docs/gradsflow/models/tracker.md, docs/overrides/main.html, docs/requirements.txt, gradsflow/__init__.py, gradsflow/core/data.py, gradsflow/data/base.py, gradsflow/models/__init__.py, gradsflow/models/base.py, gradsflow/models/model.py, gradsflow/models/tracker.py, gradsflow/models/utils.py, gradsflow/tuner/automodel.py, mkdocs.yml, tests/core/test_autodata.py, tests/models/test_utils.py
=> ✨ refactor data handling 📝 docs update

gradsflow/callbacks/callbacks.py, gradsflow/models/model.py, gradsflow/models/tracker.py
=> 🐍 remove callback_runner from tracker

CONTRIBUTING.md, README.md, docs/index.md, docs/overrides/main.html, mkdocs.yml
=> clean docs

gradsflow/models/base.py
=> ✨refactor base model

gradsflow/callbacks/callbacks.py, gradsflow/callbacks/gpu.py, gradsflow/models/base.py, mkdocs.yml, pyproject.toml, tests/models/test_model.py
=> ☘️ add codecarbon callback

gradsflow/models/base.py, gradsflow/models/model.py
=> fix loss compile

docs/requirements.txt, gradsflow/__init__.py, gradsflow/callbacks/raytune.py, gradsflow/tasks/autotasks.py, gradsflow/utility/imports.py, pyproject.toml
=> minor fixes

.coveragerc, examples/nbs/01-ImageClassification.ipynb, examples/src/models/hello_world.py, gradsflow/data/autodata.py, gradsflow/utility/common.py, gradsflow/utility/data.py, pyproject.toml, tests/utility/test_common.py, tests/utility/test_data.py
=> 📚 update example

examples/src/models/hello_world.py, tests/callbacks/test_logger.py, tests/models/test_model.py
=> remove dependencies

README.md, docs/index.md
Recently gradsflow was added to conda-forge (PR: https://github.com/conda-forge/staged-recipes/pull/17215). 
This PR updates 
Fixes/related to #138 (issue).
> I could not find any `CHANGELOG` file? Where is it? @aniketmaurya
=> added conda installation instruction

pyproject.toml
=> pin flash version to 0.5.1

.github/pull_request_template.md, .github/workflows/main.yml, .github/workflows/publish-to-pypi.yml, MANIFEST.in, Makefile, pyproject.toml, setup.cfg, setup.py
=> Remove flit

gradsflow/models/tracker.py
=> remove redundant to_item 

examples/src/tasks/image_classifier.py, gradsflow/callbacks/base.py, gradsflow/callbacks/gpu.py, gradsflow/callbacks/logger/comet.py, gradsflow/callbacks/logger/logger.py, gradsflow/callbacks/progress.py, gradsflow/callbacks/raytune.py, gradsflow/callbacks/runner.py, gradsflow/callbacks/training.py, gradsflow/core/__init__.py, gradsflow/core/base.py, gradsflow/models/base.py, gradsflow/models/model.py, gradsflow/models/tracker.py, gradsflow/utility/common.py, tests/callbacks/test_runner.py, tests/conftest.py, tests/models/test_tracker.py
=> refactor Tracker

examples/nbs/01-ImageClassification.ipynb, examples/nbs/05-model_fit.ipynb, examples/src/models/hello_world.py, gradsflow/models/base.py, gradsflow/models/model.py, tests/models/test_model.py
Fixes #157 - removed deprecated examples
=> 📝  fix documentation & examples

gradsflow/core/metrics.py, gradsflow/data/autodata.py, gradsflow/models/base.py, gradsflow/models/model.py
- Create a `MetricsContainer` class which will handle all the metrics related operations.
- Model is a Facade which contains MetricsContainer
=> refactor metrics

gradsflow/callbacks/progress.py, gradsflow/data/autodata.py, gradsflow/data/base.py, gradsflow/utility/common.py
- Expose train and val dataloader length from `AutoDataset` using property
=> add dataoader length

gradsflow/callbacks/logger/logger.py, tests/callbacks/test_logger.py
- `ModelCheckpoint` callback fails if the provided path is not available.
- This PR will create a folder if it doesn't exist
=> fix model checkpoint folder not found

gradsflow/core/metrics.py
[Metrics](https://github.com/gradsflow/gradsflow/blob/4f2418fb0bd60d822188118f2d10113ed40a57a1/gradsflow/core/metrics.py#L37) was reinitializing metrics instead of resetting values.
Fixed with this PR.
=> Fix metrics update

gradsflow/models/model.py
https://github.com/gradsflow/gradsflow/blob/bd2fb05bcce9f8d34443cc991fb680f6825871df/gradsflow/models/tracker.py#L24
`current_epoch` was not updated after each epoch
=> increment current_epoch after each epoch

docs/CHANGELOG.md, docs/gradsflow/callbacks.md, gradsflow/callbacks/__init__.py, gradsflow/callbacks/comet.py, gradsflow/callbacks/logger.py, gradsflow/callbacks/training.py, gradsflow/callbacks/wandb.py
=> 🌟  format docs

README.md, docs/index.md
=> update docs :memo:

examples/nbs/01-ImageClassification.ipynb, examples/nbs/02-TextClassification.ipynb, examples/nbs/03-TextSummarization.ipynb, examples/nbs/04-RayDataset.ipynb, examples/src/tasks/text_classification.py, gradsflow/autotasks/autoclassification/text/text.py, gradsflow/autotasks/engine/backend.py, tests/autotasks/test_autotrainer.py, tests/autotasks/test_core_automodel.py
* Use Flash trainer with Flash models
* Fix examples
=> fix examples and Flash trainer

examples/src/models/hello_world.py, gradsflow/autotasks/engine/backend.py, gradsflow/data/autodata.py, gradsflow/models/base.py, gradsflow/models/model.py, gradsflow/utility/common.py, pyproject.toml, setup.cfg, tests/__main__.py, tests/autotasks/test_core_automodel.py, tests/data/test_autodata.py, tests/data/test_image_data.py, tests/data/test_ray_dataset.py, tests/models/test_model.py
* Refactor code base
* Remove Flash
* Remove HF Accelerate
* Integrate Fabric
* Fix test cases
=> refactor Accelerator with Fabric

examples/src/models/hello_world.py, gradsflow/data/autodata.py, gradsflow/data/mixins.py, gradsflow/models/base.py, gradsflow/models/model.py, gradsflow/tuner/automodel.py, tests/models/test_model.py
=> Test fabric
